version: "3.9"
services:
  haproxy:
    image: pridekk/haproxy:0.1
    volumes:
    - ./load_balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8888:8888"

  mongo:
    image: mongo:4.4.13
    restart: always
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  investment:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    entrypoint: [ "npm", "start" ]
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
    ports:
      - "8082:3001"
networks:
  default: