version: "3.9"
services:
  haproxy:
    image: haproxy:2.5.5
    volumes:
    - ./load_balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8888:8888"

  mongo:
    image: mongo:4.4.13
    restart: always
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  investment:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    entrypoint: [ "npm", "start" ]
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
      REDIS_URL: "redis://redis:6379"
    # ports: # replica 모드에서는 주석처리해야함
    #   - "8082:3001"
    deploy:
      mode: replicated
      replicas: 2 
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8099:8081"
    environment:
      REDIS_HOSTS: redis:redis:6379
networks:
  default: